spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: demo-service
          uri: lb://demo-service
          predicates:
            - Path=/employee/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
  instance:
    ip-address: localhost

server:
  port: 8082
